kind: pipeline
type: docker
name: default

steps:
- name: test-build
  image: node
  commands: 
    - npm install -g pnpm
    - pnpm install
    - pnpm format:check
    - pnpm lint:astro
    - pnpm build
