kind: pipeline
type: docker
name: default

trigger:
  branch:
    - main

steps:
  - name: test
    image: node
    commands: 
      - npm install -g pnpm
      - pnpm install
      - pnpm format:check
      - pnpm lint:astro

  - name: release
    image: plugins/gitea-release
    depends_on:
       - test
    when:
      ref:
        - refs/tags/*   
    environment:
      GITEA_API_KEY:
        from_secret: gitea_api_key
      GITEA_BASE_URL: 
        from_secret: gitea_base_url
    settings:
      api_key: 
        from_secret: gitea_api_key
      base_url: 
        from_secret: gitea_base_url
      files: dist/*

  - name: docker  
    image: plugins/docker
    privileged: true
    depends_on:
       - test
    environment:
      USERNAME:
        from_secret: gitea_username
      PASSWORD:
        from_secret: gitea_password
      GITEA_BASE_URL: 
        from_secret: gitea_base_url
    settings:
      tags: latest
      auto_tag: true
      repo: git.littlevibe.net/kuhree/www
      registry: git.littlevibe.net 
      username: 
        from_secret: gitea_username
      password: 
        from_secret: gitea_password
